### ISSUE TITLE
Question: does a streaming newline-delimited parser exist?

### ISSUE THREAD

**Issue by holtkamp** [clue/reactphp-flux#9]
Maybe a noob question, but after reading:
- https://www.lueck.tv/2018/introducing-reactphp-flux
- https://www.lueck.tv/2018/introducing-ndjson-reactphp

and looking at libraries with streaming support for specific file formats like:

- https://github.com/Rakdar/reactphp-csv
- https://github.com/clue/reactphp-ndjson

I was wondering whether a simple streaming newline-delimited parser exists that "just" takes a text file with an entry on each line into account?

**Comment by clue** [comment]
Very good question indeed!

If you want to process a plain text file (such as a log file), you may want to look into using @legionth's https://github.com/legionth/php-line-react.

If you're in control of generating the stream, you may still want to consider using a structured format so that you can add new fields to your records in the future. For example, the following is a valid NDJSON stream with three string elements:

```json
"first"
"second"
"third"
```

I hope this helps :+1:

**Comment by holtkamp** [comment]
Yeah, that was what I was looking for. Maybe good to mention this simple approach in the examples before discussing to the "advanced" `NDJSON` examples. 

Thanks for the quick and detailed response!
